### ISSUE TITLE
v1.1 Recent Recipe List - Limit Appended List Size

### ISSUE THREAD

**Issue by paperpatch** [paperpatch/open_fridge#41]
Currently, the appended recent recipe list can become overwhelming as there's no limit to adding recipes.
It currently unshifts() the list. Perhaps pop() the list after it hits a certain limit?

Make a limit to the appended list.

**Comment by gauravkmjaiswal** [comment]
can i take this issue ,On completion this will be my first open source contribution

**Comment by BrandonConte** [comment]
Taking a crack at this now.
